### PR TITLE
Create URLConnectionReader

### PR DESCRIPTION
**Pull request by Sdspier**

### CODE REVIEW

**Comment by tstormz** [comment]
i gave you permission to push

**Comment by Sdspier** [comment]
Thanks, I do like pushing

**Comment by tstormz** [comment]
lol, heres the regex code I stole from Jayme:

inputLine = inputLine.replaceAll("\\<.*?>", "");
            inputLine = inputLine.replaceAll("\\<.*[\\r\\n]+","");
            String[] words = inputLine.split("\\s+");
            for ( int i = 0; i < words.length; i++ ) {
                System.out.println(words[i]);
            }

**Comment by Sdspier** [comment]
Cool, I'm working on my own version right now

**Comment by tstormz** [comment]
the code doesn't cut out everything. If the closing tag ">" is on a
separate line then the regex doesn't find it.

I'm trying to cut out parts of code that don't have content first (such as
<script> <!-- )

**Comment by Sdspier** [comment]
Sure, I'm just spitting out code to get the ball rolling

**Pull request merged**
